"""Reproduce the Rust Keccak-transcript challenges in Python.

The expected challenges are generated by the Rust test ``export_transcript_vector``
(reference/fixtures/transcript_vector.json). This test drives the Python
:class:`pyvega.transcript.Transcript` through the identical schedule and asserts
byte-for-byte equal challenges.

Run with:  python3 reference/tests/test_transcript.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.dirname(HERE)
sys.path.insert(0, REF)

from pyvega.transcript import Transcript, updated_state, keccak256  # noqa: E402
from pyvega.curve import generator  # noqa: E402
from pyvega.field import scalar_to_repr  # noqa: E402


def hexs(v: int) -> str:
  return scalar_to_repr(v).hex()


def selftest_primitive():
# Keccak256 of the empty string is a well-known constant.
  assert (
    keccak256(b"").hex()
    == "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
  )
  # updated_state must be exactly 64 bytes.
  assert len(updated_state(b"", b"NoTRlabel")) == 64


def main():
  selftest_primitive()

  path = os.path.join(REF, "fixtures", "transcript_vector.json")
  with open(path) as f:
    exp = json.load(f)

  t = Transcript(exp["label"].encode())

  t.absorb_scalar(b"s1", 2)
  c1 = t.squeeze(b"c1")

  t.absorb_point(b"g", generator())
  t.absorb_scalars(b"vs", [7, 9])
  c2 = t.squeeze(b"c2")

  t.absorb_scalar(b"c", c1)
  t.absorb_scalar(b"c", c2)
  c3 = t.squeeze(b"c3")
  c4 = t.squeeze(b"c4")

  got = {"c1": hexs(c1), "c2": hexs(c2), "c3": hexs(c3), "c4": hexs(c4)}
  for k in ("c1", "c2", "c3", "c4"):
    status = "OK" if got[k] == exp[k] else "MISMATCH"
    print(f"  {k}: {got[k]}  [{status}]")
    assert got[k] == exp[k], f"{k}: got {got[k]}, expected {exp[k]}"

  print("\nPASS: Python transcript reproduces all Rust challenges byte-for-byte.")


if __name__ == "__main__":
  main()
